output "region" { value = var.region }
output "github_deploy_role_arn" { value = aws_iam_role.github_deploy.arn }
output "ecs_cluster_name" { value = module.ecs.cluster_name }
output "api_service_name" { value = module.ecs.service_names["api"] }
output "worker_service_name" { value = module.ecs.service_names["worker"] }
output "encoder_service_name" { value = lookup(module.ecs.service_names, "encoder", null) }
output "embedding_worker_service_name" { value = lookup(module.ecs.service_names, "embedding-worker", null) }
output "collector_service_name" { value = lookup(module.ecs.service_names, "collector", null) }
output "ecr_repository_urls" { value = module.ecs.ecr_repository_urls }
output "task_definition_arns" { value = module.ecs.task_definition_arns }
output "task_role_arns" { value = module.ecs.task_role_arns }
output "execution_role_arns" { value = module.ecs.execution_role_arns }
output "frontend_bucket_name" { value = module.s3.buckets["frontend"].name }
output "frontend_distribution_id" { value = module.cloudfront.distributions["frontend"].id }
output "media_distribution_id" { value = module.cloudfront.distributions["media"].id }
output "storage_bucket" { value = module.s3.buckets["media"].name }
output "storage_prefix" { value = var.storage_prefix }
output "cdn_domain" { value = module.cloudfront.distributions["media"].domain_name }
output "cdn_key_pair_id" { value = module.cloudfront.key_pair_id }
output "frontend_url" { value = local.frontend_url }
output "api_base_url" { value = "https://${var.api_domain}" }
output "api_alb_dns_name" { value = module.alb.dns_name }
output "rds_address" { value = module.rds.address }
output "rds_identifier" { value = module.rds.identifier }
output "rds_master_secret_arn" { value = module.rds.master_secret_arn }
output "mq_broker_id" { value = module.mq.id }
output "mq_management_url" { value = module.mq.management_url }
output "private_subnet_ids" { value = module.network.private_subnet_ids }
output "security_group_ids" { value = module.network.security_group_ids }
output "dashboard_name" { value = module.monitoring.dashboard_name }

output "task_definition_parameter_names" { value = module.ecs.task_definition_parameter_names }
