-- Adopt the existing Hibernate schema without deleting or renumbering user data.
CREATE TABLE IF NOT EXISTS user_accounts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(120) NOT NULL,
 email varchar(160) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL,
 role varchar(20) NOT NULL, created_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS team_spaces (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(120) NOT NULL,
 description varchar(800) NOT NULL, created_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS team_members (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, team_id bigint NOT NULL REFERENCES team_spaces,
 user_id bigint NOT NULL REFERENCES user_accounts, team_role varchar(20) NOT NULL,
 joined_at timestamptz NOT NULL, UNIQUE(team_id,user_id)
);
CREATE TABLE IF NOT EXISTS image_assets (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title varchar(140) NOT NULL,
 description varchar(1500) NOT NULL, category varchar(120) NOT NULL, tags varchar(1000) NOT NULL,
 original_file_name varchar(255) NOT NULL, stored_file_name varchar(255), thumbnail_file_name varchar(255),
 size_bytes bigint NOT NULL, visibility varchar(20) NOT NULL, moderation_status varchar(20) NOT NULL,
 uploader_id bigint NOT NULL REFERENCES user_accounts, team_id bigint REFERENCES team_spaces,
 created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS storage_deletion_jobs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_key varchar(600) NOT NULL,
 attempts integer NOT NULL, next_attempt_at timestamptz NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_storage_deletion_due ON storage_deletion_jobs(next_attempt_at);
