#!/usr/bin/env python3
"""Verify a populated legacy schema can migrate using the current executable JAR.

Creates and finally drops a uniquely named database on the supplied PostgreSQL
server; never migrates the database named in the admin DSN. Requires CREATEDB and
pgvector installed on that server. Runs its own API process on an unused port.

Example (after ./gradlew bootJar):
  MIGRATION_ADMIN_DATABASE_URL=postgresql://user:password@localhost:5432/postgres \
    python scripts/migration_test.py --jar backend/build/libs/app.jar
"""
import argparse
import hashlib
import io
import json
import os
from pathlib import Path
import shutil
import socket
import subprocess
import tempfile
import time
import uuid

from PIL import Image
import psycopg
from psycopg import sql
from psycopg.conninfo import conninfo_to_dict, make_conninfo
import requests

# Pre-pipeline Hibernate schema: no Flyway history, mandatory original/thumbnail
# paths, existing identity keys, memberships, moderation and durable deletion jobs.
LEGACY_SCHEMA = """
CREATE TABLE user_accounts (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(120) NOT NULL,
 email varchar(160) NOT NULL UNIQUE, password_hash varchar(255) NOT NULL,
 role varchar(20) NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE team_spaces (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name varchar(120) NOT NULL,
 description varchar(800) NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE team_members (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 team_id bigint NOT NULL REFERENCES team_spaces, user_id bigint NOT NULL REFERENCES user_accounts,
 team_role varchar(20) NOT NULL, joined_at timestamptz NOT NULL, UNIQUE(team_id,user_id));
CREATE TABLE image_assets (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title varchar(140) NOT NULL,
 description varchar(1500) NOT NULL, category varchar(120) NOT NULL, tags varchar(1000) NOT NULL,
 original_file_name varchar(255) NOT NULL, stored_file_name varchar(255) NOT NULL,
 thumbnail_file_name varchar(255) NOT NULL, size_bytes bigint NOT NULL,
 visibility varchar(20) NOT NULL, moderation_status varchar(20) NOT NULL,
 uploader_id bigint NOT NULL REFERENCES user_accounts, team_id bigint REFERENCES team_spaces,
 created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL);
CREATE TABLE storage_deletion_jobs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, object_key varchar(600) NOT NULL,
 attempts integer NOT NULL, next_attempt_at timestamptz NOT NULL);
CREATE INDEX idx_storage_deletion_due ON storage_deletion_jobs(next_attempt_at);
"""


def require(condition, message):
    if not condition:
        raise AssertionError(message)


def free_port():
    with socket.socket() as listener:
        listener.bind(("127.0.0.1", 0))
        return listener.getsockname()[1]


def snapshot(conn):
    result = {}
    for table in ("user_accounts", "team_spaces", "team_members", "storage_deletion_jobs"):
        result[table] = conn.execute(sql.SQL("SELECT * FROM {} ORDER BY id").format(sql.Identifier(table))).fetchall()
    result["image_assets"] = conn.execute("""SELECT id,title,description,category,tags,original_file_name,
        stored_file_name,thumbnail_file_name,size_bytes,visibility,moderation_status,uploader_id,team_id,
        created_at,updated_at FROM image_assets ORDER BY id""").fetchall()
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--jar", required=True, type=Path)
    parser.add_argument("--java", default=shutil.which("java") or "java")
    parser.add_argument("--api-port", type=int, default=0, help="Default: choose an unused loopback port")
    parser.add_argument("--log-file", type=Path, help="Keep this API process's log outside its temporary directory")
    args = parser.parse_args()
    jar = args.jar.resolve()
    require(jar.is_file(), "Executable JAR not found; run backend/gradlew bootJar first")
    admin_dsn = os.getenv("MIGRATION_ADMIN_DATABASE_URL") or os.getenv("TEST_DATABASE_URL")
    require(admin_dsn, "Set MIGRATION_ADMIN_DATABASE_URL to a disposable PostgreSQL server with CREATEDB")
    config = conninfo_to_dict(admin_dsn)
    host = config.get("host", "localhost")
    require(not host.startswith("/") and "," not in host, "Use one TCP PostgreSQL host for the API migration test")
    name = "photoplatform_migration_" + uuid.uuid4().hex[:12]
    migration_dsn = make_conninfo(admin_dsn, dbname=name)
    process = None
    created = False
    with tempfile.TemporaryDirectory(prefix="photoplatform-migration-") as temporary:
        root = Path(temporary)
        storage = root / "storage"
        log_path = args.log_file.resolve() if args.log_file else root / "api.log"
        log_path.parent.mkdir(parents=True, exist_ok=True)
        try:
            with psycopg.connect(admin_dsn, autocommit=True) as admin:
                admin.execute(sql.SQL("CREATE DATABASE {}").format(sql.Identifier(name)))
                created = True
            output = io.BytesIO()
            Image.new("RGB", (16, 12), "orange").save(output, "PNG")
            image_bytes = output.getvalue()
            for folder, filename in (("originals", "legacy.png"), ("thumbnails", "legacy-thumb.png")):
                target = storage / "migration-fixture" / folder / filename
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(image_bytes)
            with psycopg.connect(migration_dsn, autocommit=True) as conn:
                conn.execute(LEGACY_SCHEMA)
                conn.execute("""INSERT INTO user_accounts VALUES
                    (7001,'Legacy owner','legacy@example.test','unused-migration-fixture','USER',now());
                    INSERT INTO team_spaces VALUES (8001,'Legacy team','Keep membership and identity',now());
                    INSERT INTO team_members VALUES (9001,8001,7001,'OWNER',now());
                    INSERT INTO storage_deletion_jobs VALUES (11001,'originals/old-retired.png',2,now()+interval '10 years');""")
                for identity, visibility, moderation, team in ((10001, "PUBLIC", "APPROVED", None),
                                                               (10002, "TEAM", "APPROVED", 8001),
                                                               (10003, "PUBLIC", "PENDING", None)):
                    conn.execute("""INSERT INTO image_assets VALUES
                        (%s,'Legacy photo','Original description','Nature','legacy,orange','camera.png',
                        'legacy.png','legacy-thumb.png',%s,%s,%s,7001,%s,now(),now())""",
                                 (identity, len(image_bytes), visibility, moderation, team))
                for table in ("user_accounts", "team_spaces", "team_members", "image_assets", "storage_deletion_jobs"):
                    conn.execute(sql.SQL("SELECT setval(pg_get_serial_sequence(%s,'id'),(SELECT max(id) FROM {}))")
                                 .format(sql.Identifier(table)), (table,))
                before = snapshot(conn)
                require(conn.execute("SELECT to_regclass('flyway_schema_history')").fetchone()[0] is None,
                        "Fixture must not contain Flyway history")
            api_port = args.api_port or free_port()
            env = os.environ.copy()
            env.update({"PORT": str(api_port), "MANAGEMENT_PORT": "0", "APP_SEED_ENABLED": "false",
                        "MEDIA_PIPELINE_ENABLED": "false", "SEMANTIC_SEARCH_ENABLED": "false",
                        "STORAGE_PROVIDER": "local", "STORAGE_ROOT": str(storage), "STORAGE_PREFIX": "migration-fixture",
                        "SPRING_DATASOURCE_URL": f"jdbc:postgresql://{host}:{config.get('port', '5432')}/{name}",
                        "SPRING_DATASOURCE_USERNAME": config.get("user", "generatecloud"),
                        "SPRING_DATASOURCE_PASSWORD": config.get("password", ""),
                        "JPA_DDL_AUTO": "validate", "OTEL_SDK_DISABLED": "true"})
            base = f"http://127.0.0.1:{api_port}"
            with log_path.open("w") as log:
                process = subprocess.Popen([args.java, "-jar", str(jar), "--server.address=127.0.0.1"],
                                           cwd=root, env=env, stdout=log, stderr=subprocess.STDOUT)
                deadline = time.monotonic() + 120
                while time.monotonic() < deadline:
                    if process.poll() is not None:
                        raise RuntimeError("Migration API exited before readiness")
                    try:
                        if requests.get(base + "/readyz", timeout=2).status_code == 200:
                            break
                    except requests.RequestException:
                        pass
                    time.sleep(.5)
                else:
                    raise TimeoutError("Migration API did not become ready within 120 seconds")
                with psycopg.connect(migration_dsn) as conn:
                    require(snapshot(conn) == before, "Migration changed legacy records, IDs, object paths or timestamps")
                    require(conn.execute("SELECT count(*) FROM user_accounts").fetchone()[0] == 1,
                            "Migration unexpectedly enabled demo seeding")
                    history = conn.execute("SELECT version,success FROM flyway_schema_history ORDER BY installed_rank").fetchall()
                    require(all(success for _, success in history), "A Flyway migration failed")
                    require({"0", "1", "2", "3", "4"}.issubset({version for version, _ in history}),
                            "Expected baseline version 0 and all four migration versions")
                    statuses = conn.execute("SELECT storage_layout,processing_status,asset_version,deleted_at FROM image_assets").fetchall()
                    require(all(row == ("LEGACY", "READY", 1, None) for row in statuses), "Legacy defaults are incorrect")
                    paths = conn.execute("""SELECT is_nullable FROM information_schema.columns WHERE table_name='image_assets'
                        AND column_name IN ('stored_file_name','thumbnail_file_name')""").fetchall()
                    require(paths == [("YES",), ("YES",)], "Direct uploads still require old storage paths")
                    require(conn.execute("SELECT count(*) FROM media_processing_jobs").fetchone()[0] == 0,
                            "Migration unexpectedly scheduled legacy reprocessing")
                response = requests.get(base + "/api/files/10001", timeout=10)
                require(response.status_code == 200 and response.content == image_bytes,
                        "Legacy public original cannot be read byte-for-byte after migration")
                response = requests.get(base + "/api/files/10001/thumbnail", timeout=10)
                require(response.status_code == 200 and response.content == image_bytes, "Legacy thumbnail delivery changed")
                for identity in (10002, 10003):
                    require(requests.get(base + f"/api/files/{identity}", timeout=10).status_code == 403,
                            "Migration exposed team-only or pending legacy media")
                response = requests.post(base + "/api/auth/register", json={"name": "After migration",
                                         "email": "after-migration@example.test", "password": "migration-password-123"}, timeout=10)
                require(response.status_code == 200, "Registration failed after migration (identity sequence or schema regression)")
                with psycopg.connect(migration_dsn) as conn:
                    identity = conn.execute("SELECT id FROM user_accounts WHERE email='after-migration@example.test'").fetchone()[0]
                    require(identity > 7001, "Migration changed the identity sequence")
                print(json.dumps({"result": "PASS", "legacy_images_preserved": 3,
                                  "flyway_versions": [version for version, _ in history],
                                  "original_sha256": hashlib.sha256(image_bytes).hexdigest(),
                                  "legacy_delivery_and_access": "PASS", "identity_sequence": "PASS"}))
        except Exception:
            if log_path.exists():
                print("Migration API log (last 80 lines):")
                print("\n".join(log_path.read_text(errors="replace").splitlines()[-80:]))
            raise
        finally:
            if process is not None and process.poll() is None:
                process.terminate()
                try:
                    process.wait(timeout=20)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=5)
            if created:
                with psycopg.connect(admin_dsn, autocommit=True) as admin:
                    admin.execute(sql.SQL("DROP DATABASE {} WITH (FORCE)").format(sql.Identifier(name)))


if __name__ == "__main__":
    main()
